services:
  - type: web
    name: htmlsearch
    runtime: node
    plan: free
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: NODE_ENV
        value: production
